export const EXPRESSION_TYPE_FIELD = 'FIELD';
export const EXPRESSION_TYPE_NUMBER = 'NUMBER';
export const EXPRESSION_TYPE_STRING = 'STRING';
export const EXPRESSION_TYPE_PLACEHOLDER = 'PLACEHOLDER';

export const ALL_EXPRESSION_TYPES = [
  EXPRESSION_TYPE_FIELD,
  EXPRESSION_TYPE_NUMBER,
  EXPRESSION_TYPE_STRING,
  EXPRESSION_TYPE_PLACEHOLDER,
] as const;

export type ExpressionType = (typeof ALL_EXPRESSION_TYPES)[number];
