export const LOGICAL_OPERATOR_EQUALS = 'EQUALS';
export const LOGICAL_OPERATOR_NOT_EQUALS = 'NOT_EQUALS';
export const LOGICAL_OPERATOR_GREATER_THAN = 'GREATER_THAN';
export const LOGICAL_OPERATOR_LESS_THAN = 'LESS_THAN';

export const LOGICAL_OPERATOR_NULL = 'NULL';
export const LOGICAL_OPERATOR_NOT_NULL = 'NOT_NULL';
export const LOGICAL_OPERATOR_BLANK = 'BLANK_NULL';
export const LOGICAL_OPERATOR_NOT_BLANK = 'NOT_BLANK';

export const ALL_LOGICAL_OPERATORS = [
  LOGICAL_OPERATOR_EQUALS,
  LOGICAL_OPERATOR_NOT_EQUALS,
  LOGICAL_OPERATOR_GREATER_THAN,
  LOGICAL_OPERATOR_LESS_THAN,
] as const;

export type LogicalOperator = (typeof ALL_LOGICAL_OPERATORS)[number];
