export const PARAM_SOURCE_TYPE_USER_TEXT = 'USER_TEXT';
export const PARAM_SOURCE_TYPE_DEFINED_GROUP = 'DEFINED_GROUP';
export const PARAM_SOURCE_TYPE_REQ_REP = 'REQ_REP';

export const ALL_PARAM_SOURCE_TYPES = [
  PARAM_SOURCE_TYPE_USER_TEXT,
  PARAM_SOURCE_TYPE_DEFINED_GROUP,
  // PARAM_SOURCE_TYPE_REQ_REP,
] as const;

export type ParamSourceType = (typeof ALL_PARAM_SOURCE_TYPES)[number];
